name: env_tutorial
on: [pull_request, push]

env:
  API_KEY: MA_CLE_SECRETE_123

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step 1
        run: echo "The API key is ${{ env.API_KEY }}"

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: step 1
        run: echo "The API key is $API_KEY"
